owner: clann-inc
repo: tcm-upptime

sites:
  - name: tcm-prd
    url: http://tcm-prd.clann-inc.com/
  - name: tcm-stg
    url: http://tcm-stg.clann-inc.com/

status-website:
  baseUrl: /tcm-upptime
  logoUrl: https://clann.werte.jp/wp-content/uploads/2020/07/logo.svg
  name: PRJ監視
  introTitle: ウェブサイト死活監視システム
  introMessage: 次のサイトの死活監視状況。5分毎にチェックしています。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
